### ISSUE TITLE
Failed to activate the spacegray-chalk-syntax theme

### ISSUE THREAD

**Issue by rdk5** [vyder/spacegray-chalk#2]
[Enter steps to reproduce below:]
1. Install theme
2. Activate them under "Syntax Theme" drop down menu
3. Errors pop up

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.3
**Thrown From**: [spacegray-chalk-syntax](https://github.com/vyder/spacegray-chalk) package, v4.0.1
### Stack Trace

Failed to activate the spacegray-chalk-syntax theme

```
At './stylesheets/base.less' wasn't found in /Users/rickykharawala/.atom/packages/spacegray-chalk-syntax/index.less:1:0

LessError: './stylesheets/base.less' wasn't found
  at /Users/rickykharawala/.atom/packages/spacegray-chalk-syntax/index.less:1:0
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "spacegray-chalk-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by vyder** [comment]
Also fixed all the deprecation warnings this package was generating. Thanks for pointing out this bug!
